platform :ios, '13.4'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'WiFiHandshakeCapture' do
  config = use_native_modules!

  use_react_native!(
    :path => config['reactNativePath'],
    :hermes_enabled => true,
    :fabric_enabled => true
  )

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'libpcap', :git => 'https://github.com/libpcap/libpcap.git'

  target 'WiFiHandshakeCaptureTests' do
    inherit! :complete
  end
end

target 'WifiCaptureExtension' do
  inherit! :complete
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'libpcap', :git => 'https://github.com/libpcap/libpcap.git'
end

post_install do |installer|
  react_native_post_install(installer, :mac_catalyst_enabled => false)
end
